kind: ConfigMap
apiVersion: v1
data:
    backend-protocol: h2
    tls-alpn: h2,http/1.1
    use-htx: "true"
    dynamic-scaling: "true"
    backend-server-slots-increment: "4"
    http-port: "8080"
    https-port: "8443"
    stats-port: "1936"
metadata:
  name: haproxy-configmap