apiVersion: v1
kind: Service
metadata:
  labels:
    run: haproxy-ingress
  name: haproxy-ingress
spec:
  type: NodePort
  ports:
  - name: port-1
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31080
  - name: port-2
    port: 8443
    protocol: TCP
    targetPort: 8443
    nodePort: 31443
  - name: port-3
    port: 1936
    protocol: TCP
    targetPort: 1936
    nodePort: 31736
  selector:
    run: haproxy-ingress