apiVersion: v1
kind: Service
metadata:
  labels:
    run: haproxy-ingress
  name: haproxy-ingress
  namespace: demo
spec:
  type: NodePort
  ports:
  - name: port-1
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  - name: port-2
    port: 8443
    protocol: TCP
    targetPort: 8443
    nodePort: 30443
  - name: port-3
    port: 1936
    protocol: TCP
    targetPort: 1936
    nodePort: 31936
  selector:
    run: haproxy-ingress